# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control.proto',
  package='vss_control',
  syntax='proto2',
  serialized_pb=_b('\n\rcontrol.proto\x12\x0bvss_control\")\n\x04Pose\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\"\xac\x01\n\x0cUser_Control\x12\x0e\n\x06paused\x18\x01 \x01(\x08\x12(\n\rnew_ball_pose\x18\x02 \x01(\x0b\x32\x11.vss_control.Pose\x12/\n\x14new_robots_blue_pose\x18\x03 \x03(\x0b\x32\x11.vss_control.Pose\x12\x31\n\x16new_robots_yellow_pose\x18\x04 \x03(\x0b\x32\x11.vss_control.Pose')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='vss_control.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='vss_control.Pose.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='vss_control.Pose.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='vss_control.Pose.yaw', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=71,
)


_USER_CONTROL = _descriptor.Descriptor(
  name='User_Control',
  full_name='vss_control.User_Control',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paused', full_name='vss_control.User_Control.paused', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_ball_pose', full_name='vss_control.User_Control.new_ball_pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_robots_blue_pose', full_name='vss_control.User_Control.new_robots_blue_pose', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_robots_yellow_pose', full_name='vss_control.User_Control.new_robots_yellow_pose', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=246,
)

_USER_CONTROL.fields_by_name['new_ball_pose'].message_type = _POSE
_USER_CONTROL.fields_by_name['new_robots_blue_pose'].message_type = _POSE
_USER_CONTROL.fields_by_name['new_robots_yellow_pose'].message_type = _POSE
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['User_Control'] = _USER_CONTROL

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
  DESCRIPTOR = _POSE,
  __module__ = 'control_pb2'
  # @@protoc_insertion_point(class_scope:vss_control.Pose)
  ))
_sym_db.RegisterMessage(Pose)

User_Control = _reflection.GeneratedProtocolMessageType('User_Control', (_message.Message,), dict(
  DESCRIPTOR = _USER_CONTROL,
  __module__ = 'control_pb2'
  # @@protoc_insertion_point(class_scope:vss_control.User_Control)
  ))
_sym_db.RegisterMessage(User_Control)


# @@protoc_insertion_point(module_scope)
