# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='state.proto',
  package='vss_state',
  syntax='proto2',
  serialized_pb=_b('\n\x0bstate.proto\x12\tvss_state\")\n\x04Pose\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\"L\n\nBall_State\x12\x1d\n\x04pose\x18\x01 \x02(\x0b\x32\x0f.vss_state.Pose\x12\x1f\n\x06v_pose\x18\x02 \x01(\x0b\x32\x0f.vss_state.Pose\"M\n\x0bRobot_State\x12\x1d\n\x04pose\x18\x01 \x02(\x0b\x32\x0f.vss_state.Pose\x12\x1f\n\x06v_pose\x18\x02 \x01(\x0b\x32\x0f.vss_state.Pose\"\x90\x01\n\x0cGlobal_State\x12$\n\x05\x62\x61lls\x18\x01 \x03(\x0b\x32\x15.vss_state.Ball_State\x12-\n\rrobots_yellow\x18\x02 \x03(\x0b\x32\x16.vss_state.Robot_State\x12+\n\x0brobots_blue\x18\x03 \x03(\x0b\x32\x16.vss_state.Robot_State')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='vss_state.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='vss_state.Pose.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='vss_state.Pose.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='vss_state.Pose.yaw', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=67,
)


_BALL_STATE = _descriptor.Descriptor(
  name='Ball_State',
  full_name='vss_state.Ball_State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='vss_state.Ball_State.pose', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v_pose', full_name='vss_state.Ball_State.v_pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=145,
)


_ROBOT_STATE = _descriptor.Descriptor(
  name='Robot_State',
  full_name='vss_state.Robot_State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='vss_state.Robot_State.pose', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v_pose', full_name='vss_state.Robot_State.v_pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=224,
)


_GLOBAL_STATE = _descriptor.Descriptor(
  name='Global_State',
  full_name='vss_state.Global_State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='balls', full_name='vss_state.Global_State.balls', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robots_yellow', full_name='vss_state.Global_State.robots_yellow', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robots_blue', full_name='vss_state.Global_State.robots_blue', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=371,
)

_BALL_STATE.fields_by_name['pose'].message_type = _POSE
_BALL_STATE.fields_by_name['v_pose'].message_type = _POSE
_ROBOT_STATE.fields_by_name['pose'].message_type = _POSE
_ROBOT_STATE.fields_by_name['v_pose'].message_type = _POSE
_GLOBAL_STATE.fields_by_name['balls'].message_type = _BALL_STATE
_GLOBAL_STATE.fields_by_name['robots_yellow'].message_type = _ROBOT_STATE
_GLOBAL_STATE.fields_by_name['robots_blue'].message_type = _ROBOT_STATE
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['Ball_State'] = _BALL_STATE
DESCRIPTOR.message_types_by_name['Robot_State'] = _ROBOT_STATE
DESCRIPTOR.message_types_by_name['Global_State'] = _GLOBAL_STATE

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
  DESCRIPTOR = _POSE,
  __module__ = 'state_pb2'
  # @@protoc_insertion_point(class_scope:vss_state.Pose)
  ))
_sym_db.RegisterMessage(Pose)

Ball_State = _reflection.GeneratedProtocolMessageType('Ball_State', (_message.Message,), dict(
  DESCRIPTOR = _BALL_STATE,
  __module__ = 'state_pb2'
  # @@protoc_insertion_point(class_scope:vss_state.Ball_State)
  ))
_sym_db.RegisterMessage(Ball_State)

Robot_State = _reflection.GeneratedProtocolMessageType('Robot_State', (_message.Message,), dict(
  DESCRIPTOR = _ROBOT_STATE,
  __module__ = 'state_pb2'
  # @@protoc_insertion_point(class_scope:vss_state.Robot_State)
  ))
_sym_db.RegisterMessage(Robot_State)

Global_State = _reflection.GeneratedProtocolMessageType('Global_State', (_message.Message,), dict(
  DESCRIPTOR = _GLOBAL_STATE,
  __module__ = 'state_pb2'
  # @@protoc_insertion_point(class_scope:vss_state.Global_State)
  ))
_sym_db.RegisterMessage(Global_State)


# @@protoc_insertion_point(module_scope)
